### ISSUE TITLE
Errors in Sublime Console on Start

### ISSUE THREAD

**Issue by olegbc1** [ihdavids/orgextended#28] opened 2021-04-01 08:29 UTC
Haven't had the time to take a look at these in detail yet, but figured I'd list them out here.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text4\Lib\python33\sublime_plugin.py", line 1494, in run_
    return self.run(edit)

  File "C:\Users\USERNAME\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orginsertselected.py", line 187, in run

  File "C:\Users\USERNAME\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orginsertselected.py", line 137, in down

AttributeError: 'OrgInput' object has no attribute 'matched'

Traceback (most recent call last):

  File "C:\Users\USERNAME\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orginsertselected.py", line 123, in on_change

  File "C:\Users\USERNAME\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orginsertselected.py", line 81, in redraw

AttributeError: 'OrgInput' object has no attribute 'matched'
```

**Comment by ihdavids** [comment] 2021-04-01 15:23
Good call.
Do you happen to recall what you were doing or what document you were looking at when that triggered? If it's on boot it could be any of the open tabs as I scan all open tabs as sublime starts.

**Comment by ihdavids** [comment] 2021-04-01 15:30
Hmmm, looks like this was an input box of some sort and you were pressing the down key but it hadn't matched any tags or something. I have guarded against the assert for now but it would be good to know more about the circumstances that caused this. (the input box is used for tags, the calendar file selection and a few other things)

**Comment by ihdavids** [comment] 2021-04-01 15:34
The changes have been pushed to the repo. The exceptions seem to happen when the system is trying to determine what to do in the tooltip box. It shouldn't throw now although the tooltip will be blank.

**Comment by olegbc1** [comment] 2021-04-01 16:37
I actually wasn't doing anything in Sublime at all. I have it open on a side screen all day and these messages are just appearing every couple of minutes or so. I could probably set my clock to it :-) Could these issues be stemming from the way path is set in `orgDirs`. I am on Windows and have it set to my Dropbox in the config file like so:
```
// Where are your org files?
"orgDirs": "c:\\Users\\olegbc\\Dropbox\\Oleg\\Org\\NewOrg",
```

Also, I saved the sublime startup log from the console just in case it may help figuring out what may be causing problems. 
[Sublime-startup-4-1-2021.log](https://github.com/ihdavids/orgextended/files/6244989/Sublime-startup-4-1-2021.log)

**Comment by ihdavids** [comment] 2021-04-01 19:06
Well that is concerning. The callstack looks like you have an input box open for some reason so you are on the date picker or inserting a tag or something. It's the tooltip help for that, that is asserting. My fix should get rid of the callstack but if this is a regular cadence we need to understand the root cause and get to the bottom of this.

Every couple of minutes makes me think this is the notifications thread (or I guess it could be an EventListener as well but that probably wouldn't be a regular cadence and probably would require some input from you)

2 Things to try here:
FIRST set this in your settings file:
"enableDebugLogging": true,

This will turn on more verbose trace logging. I don't know if that will help us here but it's worth a shot.

NEXT since I think this might be related to the notifications thread lets play with the period of that thread and see what happens. The problem here is changing the period means you have to restart sublime when you tweak it.

Open up you settings file for orgextended and add this:
- "noticePeriod": 9999

Does that make this effectively go away or not happen on a regular period?

Next thing:
- "noticePeriod": 1 (this will make it fire a notice every 60 seconds)

See if it comes back?

Would you do that for me? That can help us narrow this a little and try to validate my guess.

**Comment by ihdavids** [comment] 2021-04-01 19:08
What is annoying about that error message is that I know WHAT is causing the exception, I just don't have the context of what is causing the InputBox code to trigger.

**Comment by ihdavids** [comment] 2021-04-01 19:09
Interesting looking in your log this is certainly something to investigate:

orgDir path c does not exist!
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text4\Lib\python33\sublime_plugin.py", line 528, in on_api_ready
    plc()
  File "C:\Users\olegbc\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgextended.py", line 75, in plugin_loaded
    db.Get().RebuildDb()
  File "C:\Users\olegbc\AppData\Roaming\Sublime Text\Installed Packages\OrgExtended.sublime-package\orgdb.py", line 307, in RebuildDb
    if not Path(orgPath).exists():
  File "C:\Users\olegbc\AppData\Roaming\SUBLIM~1\Packages\pathlib\all\pathlib.py", line 1176, in exists
    self.stat()
  File "C:\Users\olegbc\AppData\Roaming\SUBLIM~1\Packages\pathlib\all\pathlib.py", line 1051, in stat
    return self._accessor.stat(self)
  File "C:\Users\olegbc\AppData\Roaming\SUBLIM~1\Packages\pathlib\all\pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ':'

**Comment by ihdavids** [comment] 2021-04-01 19:30
I found a problem orgDirs is a list, it looks like you have it set to a string.
I have a fix that will automatically handle that now.

**Comment by ihdavids** [comment] 2021-04-01 19:46
Looks like most of your problems are probably stemming from that.

**Comment by ihdavids** [comment] 2021-04-01 19:47
Okay, I think we made some progress here. These fixes will be in 1.2.6.

**Comment by olegbc1** [comment] 2021-04-02 00:00
Did I set orgDirs to a string by accident in my config somehow? Turning on verbose logging and will share them shortly

**Comment by ihdavids** [comment] 2021-04-02 04:41
Yeah, the example you gave of your config had your orgDirs set to a string vs a list of strings, but the loader didn't check and just tried to iterate over that string! :)

The hazards of a hack personal project.

**Comment by ihdavids** [comment] 2021-04-02 05:07
Pushed 1.2.6

**Comment by olegbc1** [comment] 2021-04-06 03:40
Sorry for not responding earlier. You've definitely fixed the issue, I don't see any errors in the console anymore.

**Closed as completed** 2021-04-06 03:40 UTC

**Comment by ihdavids** [comment] 2021-04-06 04:09
Great!
